version: '3'
services:
  webapp:
    image: mboyov/apache2-php74
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - /var/www/html:/var/www/html
      - ./config/php.ini:/etc/php/7.4/apache2/conf.d/30-custom.ini
      - ./config/fqdn:/etc/apache2/conf.d/fqdn
      - ./sites:/etc/apache2/sites-enabled/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080